services:
  credit-bureau:
    build:
      context: ./Unifintech/services/credit_bureau
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    ports:
      - 8080:8080
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - ./Unifintech/services/credit_bureau:/var/www/html
    working_dir: /var/www/html
